
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: 
  password: 

development:
  <<: *default
  database: eca_system_development

test:
  <<: *default
  database: eca_system_test

production:
  <<: *default
  database: eca_system_production
